# version 1.0 - all in one qmldir
# for future, split on 2 qmldir files - one for core and one for driver

files = Dir["qml/*.qml"] + Dir["threejs_driver/*.qml"]

puts "# Auto generated by generate_qmldir.rb at #{Time.now}"
puts ""

for f in files
puts "#{File.basename(f,'.qml')} 1.0 #{f}"
end